### ISSUE TITLE
error executing install-mailfilter

### ISSUE THREAD

**Issue by nerlu** [nerdoc/uberspace-tools#4]
If I want to install the install-mailfilter script I get the following error:

> sed: can't read /home/USER/etc/dspam-learn/run: No such file or directory

I executed it on a clean uberspace.

**Comment by nerdoc** [comment]
I just tested it again with a new uberspace - runs perfectly. What exactly did you do?

```
git clone https://github.com/nerdoc/uberspace-tools.git
cd uberspace-tools/
./install-mailfilter
```

And all should be done.

**Comment by nerlu** [comment]
Yeah, now it works! I don't know what went wrong....

Thank you for the fast help.
