### ISSUE TITLE
How to use mailfilter with mailboxes?

### ISSUE THREAD

**Issue by aggsol** [nerdoc/uberspace-tools#6]
I guess I have to rename something like `mailfilter-EXT`?

**Comment by nerdoc** [comment]
I don't know exactly what you mean... the mailfilter script AFAIK checks if a mail user (=EXT mailbox) is affected and uses that - **IF** you call mailfilter in the address' qmail file.
Make sure you have a .qmail-myuser file with "|mailfilter" content for your user, or easier, put that in your .qmail-default file, to call mailfilter for all email adresses that are not checked by another qmail file.

Does that answer your question? (this is no uberspace-tools bug, is it?)

**Comment by aggsol** [comment]
I have to try again, it worked perfectly on the default mailbox but not on the additional virtual mailbox.

**Comment by nerdoc** [comment]
@aggsol did it work? Can we close this issue?

**Comment by aggsol** [comment]
I didn't get spam filtering to work at all. I gave up you can close it.

**Comment by nerdoc** [comment]
Oh, funny, I have many uberspace accounts, and use this script on all of them from the start. It works without any problem, using thunderbird, and "|maildrop" in the default mailbox.
A simple

    echo -n "|maildrop" > ~/.qmail-default

should do the trick...
